name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 22              
  FRONTEND_DIR: "./frontend"
  BACKEND_DIR: "./backend"

jobs:
  backend-ci:
    name: Backend - CI (Nest.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BACKEND_DIR }}
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Lint Backend
        run: npm run lint

      - name: Test Backend with Coverage
        run: npm run test:cov

      - name: Security Audit Backend
        run: npm audit --audit-level=high || true

      - name: Build Backend
        run: npm run build

  frontend-ci:
    name: Frontend - CI (Next.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Lint Frontend
        run: npm run lint

      - name: Test Frontend with Coverage
        run: npm run test:cov

      - name: Security Audit Frontend
        run: npm audit --audit-level=high || true

      - name: Build Frontend
        run: npm run build

  deploy-backend:
    name: Deploy Backend (Railway)
    runs-on: ubuntu-latest
    needs: backend-ci
    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v4.2.2
        with:
          path: ${{ env.BACKEND_DIR }}

      - name: Deploy to Railway
        uses: railwayapp/action@v1
        with:
          service: meu-backend
          token: ${{ secrets.RAILWAY_TOKEN }}
        # Se necessário, adicione comandos customizados para deploy via CLI aqui

  deploy-frontend:
    name: Deploy Frontend (Vercel)
    runs-on: ubuntu-latest
    needs: frontend-ci
    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v4.2.2
        with:
          path: ${{ env.FRONTEND_DIR }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ${{ env.FRONTEND_DIR }}
